[package]
name = "showcase_tabs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zellij-tile = "0.40.0"
itertools = "0.12"
zellij_widgets = {path = "../../"}


