name: Continuous Integration

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:

# ensure that the workflow is only triggered once per PR,  subsequent pushes to the PR will cancel
# and restart the workflow. See https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  # don't install husky hooks during CI as they are only needed for for pre-push
  CARGO_HUSKY_DONT_INSTALL_HOOKS: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        if: github.event_name != 'pull_request'
        uses: actions/checkout@v4
      - name: Checkout
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - name: Install cargo-make
        uses: taiki-e/install-action@cargo-make
      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2
      - name: Check formatting
        run: cargo make lint-format
      - name: Check documentation
        run: cargo make lint-docs
      - name: Check conventional commits
        uses: crate-ci/committed@master
        with:
          args: "-vv"
          commits: HEAD
      - name: Check typos
        uses: crate-ci/typos@master
      - name: Lint dependencies
        uses: EmbarkStudios/cargo-deny-action@v1

  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Install cargo-make
        uses: taiki-e/install-action@cargo-make
      - name: Run cargo make clippy-all
        run: cargo make clippy

  check:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        toolchain: [ "1.70.0", "stable" ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust {{ matrix.toolchain }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: Install cargo-make
        uses: taiki-e/install-action@cargo-make
      - name: Run cargo make check
        run: cargo make check
        env:
          RUST_BACKTRACE: full

  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        toolchain: [ "1.70.0", "stable" ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust ${{ matrix.toolchain }}}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: Install cargo-make
        uses: taiki-e/install-action@cargo-make
      - name: Install cargo-nextest
        uses: taiki-e/install-action@nextest
      - name: Test 
        run: cargo test
        env:
          RUST_BACKTRACE: full
